app = "financehub-1764830114"

[build]
  image = ""

[[services]]
  internal_port = 8050
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Note: Replace `app` value with your desired Fly app name or run `flyctl launch` to initialize and overwrite this file.